--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ItIs-Dev/VanillaMobs
build-by-default: true
branches:
- main
projects:
  VanillaMobs:
    path: ""
    plugins:
     - src: customiesdevs/customies/Customies
       version: ^1.4.0
       branch: master
...
