--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ItIs-Dev/VanillaMobs
build-by-default: true
branches:
- main
projects:
  VanillaMobs:
    path: ""
    libs:
     - src: CustomiesDevs/Customies/Customies
       version: ^5.1.0
...
